- name: Copy Redis Yum Repo File
  ansible.builtin.template:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: Replace Listen address in Redis Configuration file
  ansible.builtin.replace:
    path:  "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Start Redis Service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes