- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Import Common App Setup Configuration
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install Python Dependencies
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Change the User ID and GID in App Config
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^{{item.key}}'
    line: uid = {{item.line}}
  loop:
    - {key: uid, line: "uid = {{app_user.uid}}"}
    - {key: gid, line: "gid = {{app_user.group}}"}


- name: SystemD Setup for {{ COMPONENT }} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd